---
name: Build container image
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Containerfile
      - .github/workflows/build.yaml
      - landmarks.yaml
      - translocators.yaml
permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
concurrency:
  group: build
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
        with:
          context: .
          file: ./Containerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/tof-map:latest
      - name: Clean up old images
        uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5
        with:
          package-name: tof-map
          package-type: container
          min-versions-to-keep: 5
          delete-only-untagged-versions: 'true'
