---
name: PR check
on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - main
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
      - name: Run hk checks
        run: hk check --from-ref ${{ github.event.pull_request.base.sha }} --to-ref
          ${{ github.event.pull_request.head.sha }}
      - name: npm ci
        run: npm ci
      - name: npm run build
        run: npm run build
